# Generated by Django 3.2 on 2021-04-28 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('slug', models.SlugField(default='', verbose_name='slug')),
                ('m_type', models.CharField(default='Movie', max_length=32, verbose_name='Type')),
                ('releasedate', models.DateField(verbose_name='Release date')),
                ('language', models.CharField(choices=[('ar-AE', 'Arabic (United Arab Emirates)'), ('bn-BD', 'Bengali (Bangladesh)'), ('bn-IN', 'Bengali (India)'), ('zh-CN', 'Chinese (China)'), ('en-US', 'English (United States)'), ('fr-FR', 'French (France)'), ('de-DE', 'German (Germany)'), ('hi', 'Hindi (India)'), ('id', 'Indonesian (Indonesia)'), ('ja', 'Japanese (Japan)'), ('ko-KR', 'Korean (South Korea)'), ('pt-PT', 'Portuguese (Portugal)'), ('es-ES', 'Spanish (Spain)'), ('ta-IN', 'Tamil (India)'), ('th', 'Thai (Thailand)')], default='en-US', max_length=32, verbose_name='Language')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, help_text='Designates weather this user is premium', verbose_name='Premium')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movietitle', models.CharField(max_length=128, verbose_name='Movie title')),
                ('releasedate', models.DateField(verbose_name='Release date')),
                ('language', models.CharField(choices=[('ar-AE', 'Arabic (United Arab Emirates)'), ('bn-BD', 'Bengali (Bangladesh)'), ('bn-IN', 'Bengali (India)'), ('zh-CN', 'Chinese (China)'), ('en-US', 'English (United States)'), ('fr-FR', 'French (France)'), ('de-DE', 'German (Germany)'), ('hi', 'Hindi (India)'), ('id', 'Indonesian (Indonesia)'), ('ja', 'Japanese (Japan)'), ('ko-KR', 'Korean (South Korea)'), ('pt-PT', 'Portuguese (Portugal)'), ('es-ES', 'Spanish (Spain)'), ('ta-IN', 'Tamil (India)'), ('th', 'Thai (Thailand)')], default='en-US', max_length=32, verbose_name='Language')),
                ('accepted', models.BooleanField(default=False, help_text='Designates weather this request is acccepted or not.', verbose_name='Accepted')),
                ('acceptedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted', to=settings.AUTH_USER_MODEL, verbose_name='Accepted by')),
                ('requestedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Title')),
                ('slug', models.SlugField(default='', verbose_name='Slug')),
                ('p_type', models.CharField(default='Playlist', max_length=32, verbose_name='Type')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Description')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('movies', models.ManyToManyField(blank=True, to='myapp.Movie', verbose_name='Movies')),
            ],
        ),
    ]
