# Generated by Django 3.2 on 2021-04-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmovie',
            name='rejected',
            field=models.BooleanField(default=False, help_text='Designates weather this request is rejected.', verbose_name='Rejected'),
        ),
        migrations.AlterField(
            model_name='requestmovie',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Designates weather this request is acccepted.', verbose_name='Accepted'),
        ),
    ]
