# Generated by Django 3.2 on 2021-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210429_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmovie',
            name='releasedate',
            field=models.DateField(help_text='mm / dd / yyyy', verbose_name='Release date'),
        ),
    ]
